pipeline {
    agent any

    environment {
        HELM_CHART_PATH = 'helm/flask-app'
        RELEASE_NAME = 'my-flask-app'
        NAMESPACE = 'flask-app'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/vivek-msra/flask-microservice.git', branch: 'main'
            }
        }

        stage('Deploy via Helm') {
            steps {
                sh """
                kubectl config use-context k3d-test-us-west-2-green
                helm upgrade --install ${RELEASE_NAME} ${HELM_CHART_PATH} \
                    --namespace ${NAMESPACE} --create-namespace \
                    --set image.tag=${IMAGE_TAG}
                """
            }
        }
    }
}
